name: Yath
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8352222752291709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.46539279352873564
  saturation: 0.8210777249187231
  rhythmicContrast: 0.5
purpose: []
