name: Yath
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#25282f'
    - '#8b8fa2'
    - '#ffffff'
    - '#616570'
  brandStrength: 0.5
  lightness: 0.46539279352873564
  saturation: 0.8210777249187231
  rhythmicContrast: 0.5
purpose: []
